// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ6xIVCzMRQ-Ci0tSU8MWnvfHpZpUBYa4',
    appId: '1:52870840751:web:d2e5e821aa86ea1f03af5a',
    messagingSenderId: '52870840751',
    projectId: 'getx-2c208',
    authDomain: 'getx-2c208.firebaseapp.com',
    storageBucket: 'getx-2c208.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPb2PVL3UtcZvGyIW4zQmW19FM7Rvl75E',
    appId: '1:52870840751:android:87782abe82a30fa003af5a',
    messagingSenderId: '52870840751',
    projectId: 'getx-2c208',
    storageBucket: 'getx-2c208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvrFddBtwUi2G-HcsKoDMJa4nEs5qvjl8',
    appId: '1:52870840751:ios:ea45271049098aed03af5a',
    messagingSenderId: '52870840751',
    projectId: 'getx-2c208',
    storageBucket: 'getx-2c208.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvrFddBtwUi2G-HcsKoDMJa4nEs5qvjl8',
    appId: '1:52870840751:ios:9e4b25978f3f86cb03af5a',
    messagingSenderId: '52870840751',
    projectId: 'getx-2c208',
    storageBucket: 'getx-2c208.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
